### ISSUE TITLE
No module named datasets

### ISSUE THREAD

**Issue by bach-zouk** [kahnchana/opl#2]
Hi,

In train.py line 30 in cifar directory, you import FGVCAircraft from datasets but it doesnt find dataset module. Am i missing something?

**Comment by kahnchana** [comment]
Hi, 

Thanks for pointing this out. I've mistakenly left over some additional code in the main file. I fixed this and updated the scripts as well with a new commit. The `train.sh` and `eval.sh` scripts should work out of the box now for the cifar directory.
