### ISSUE TITLE
Large batch size

### ISSUE THREAD

**Issue by shanice-l** [kahnchana/opl#3]
Thanks for your generous sharing of your code!

But I have a small question. If you have a really large batch size, e.g.,1024, the inner product between features would produce a huge matrix. Then it will cost a lot of memory in your device (maybe out of extent...)

How can you deal with this situation?

**Comment by kahnchana** [comment]
Thanks for your question. This is interesting. 

So for large batch size training, each batch would generally be distributed across multiple GPUs. This means that within each GPU, a portion of the batch with be used for loss computation and later combined. In this case, the inner product matrix will be restrained by the batch size per GPU, and generally this will not be too large (maybe 256 for a small network). 

In our experiments, we have tried such large batch sizes spread across multiple datasets (our ImageNet experiments in particular) and OPL did not show an additional compute overhead.

**Comment by shanice-l** [comment]
> Thanks for your question. This is interesting.
> 
> So for large batch size training, each batch would generally be distributed across multiple GPUs. This means that within each GPU, a portion of the batch with be used for loss computation and later combined. In this case, the inner product matrix will be restrained by the batch size per GPU, and generally this will not be too large (maybe 256 for a small network).
> 
> In our experiments, we have tried such large batch sizes spread across multiple datasets (our ImageNet experiments in particular) and OPL did not show an additional compute overhead.

Thank you for your timely reply! But things are more complicated for me. I am trying to apply OPL in a coordinate classification problem, and the size of the coordinate is B\*3\*64\*64. After flattening, the size will be (B*64*64)*3. I just find it's too hard to run high dimension matrix multiplication within a single GPU.

My situation is so particular, I'm afraid OPL is not suitable for me. I'm so sorry. But it won't affect that OPL is great work.
